import Head from "next/head";
import Link from "next/link";
import type {
  GetStaticPathsContext,
  GetStaticPropsContext,
  InferGetStaticPropsType,
} from "next";
import Image from "next/image";
import { gql } from "graphql-request";
import { GraphQLResponse } from "graphql-request/dist/types";
import { shopifyGraphqlRequestClient } from "src/lib/clients/graphqlRequestClient";
import InfiniteScroll from "react-infinite-scroll-component";

import { dehydrate, QueryClient } from "@tanstack/react-query";
import { shopifyClient, parseShopifyResponse } from "../lib/shopify";
import { GraphModel } from "shopify-buy";

import { getLayout } from "components/Layout/Layout";
import ProductGrid from "components/Product/ProductGrid";

import { useGetShopInfoQuery } from "src/generated/graphql";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed overflow-hidden top-0 left-0 h-screen !w-screen">
        <Image src={"/giphy.gif"} alt="homepage" layout="fill"></Image>
      </div>
    </>
  );
}

Home.getLayout = getLayout;

export const getStaticProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(
    useGetShopInfoQuery.getKey(),
    useGetShopInfoQuery.fetcher(shopifyGraphqlRequestClient)
  );

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
    revalidate: 180, // In seconds
  };
};
